version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.10
    steps:
      - checkout
      - run:
          name: Set up virtual environment
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip cache purge
      - run:
          name: Install dependencies
          command: |
            . venv/bin/activate
            pip install --no-cache-dir -r requirements.txt
      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            python -m run_tests

workflows:
  version: 2
  test_workflow:
    jobs:
      - test
